branches:
  - name: master
  - name: 'features/*'
    prerelease: true

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/github'
  - '@semantic-release/git'

verifyConditions:
  - path: '@semantic-release/github'

prepare:
  - path: '@semantic-release/changelog'
    changelogFile: CHANGELOG.md
  - path: '@semantic-release/git'
    message: 'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}'

repositoryUrl: 'git@github.com:cahyasetya/semtag-exercise.git'
