name: Release

on:
  push:
    branches:
      - master
      - 'features/*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install semantic-release
        run: npm install --save-dev semantic-release@18.0.0 @semantic-release/changelog @semantic-release/git

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
